version: '2.2'

services:
  db:
    image: mysql:5.7
    command:  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'

  backend:
    build: ./backend
    image: thelesik/backend:v1
    restart: always
    volumes:
      - ./backend:/backend
    env_file:
      - .env.test
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:8080'

  frontend:
    build: ./frontend
    image: thelesik/frontend:v1
    restart: always
    depends_on:
      - backend
    links:
      - backend
    ports:
      - '3000:8080'
